### PR TITLE
View model testing

### PR DESCRIPTION
**Pull request by muljo**
Not finished implementing all my tests but might as well merge my existing tests into master

### CODE REVIEW

**Comment by muljo** [comment]
I had to make getFeaturedCategories() and getSecondTierCategories() public

**Comment by scsole** [comment]
If they have been called then the public live data should be updated. Is it possible to check them instead of making helper function public?

**Comment by muljo** [comment]
@scsole I will look into it.

**Comment by scsole** [comment]
> [Dispatchers.Main testing in Kotlin](https://medium.com/swlh/kotlin-coroutines-in-android-unit-test-28ff280fc0d5)

@muljo take a look at #94. There is a test coroutine rule for this to reduce the boilerplate code in tests.

**Pull request closed without merging**
